name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clean Workspace Permissions
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }} || true
          docker run --rm -v ${{ github.workspace }}:/workspace alpine sh -c 'rm -rf /workspace/* /workspace/.*' || true
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Deploying to PRODUCTION"
            echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
            echo "COMPOSE_PROJECT_NAME=prod" >> $GITHUB_ENV
            echo "APP_PORT=7860" >> $GITHUB_ENV
          else
            echo "Deploying to DEVELOPMENT"
            echo "COMPOSE_FILE=docker-compose.mlops.yml" >> $GITHUB_ENV
            echo "COMPOSE_PROJECT_NAME=dev" >> $GITHUB_ENV
            echo "MINIO_PORT=9010" >> $GITHUB_ENV
            echo "MINIO_CONSOLE_PORT=9011" >> $GITHUB_ENV
            echo "MLFLOW_PORT=5011" >> $GITHUB_ENV
            echo "AIRFLOW_PORT=8081" >> $GITHUB_ENV
            echo "APP_PORT=7861" >> $GITHUB_ENV
          fi

      - name: Build Docker Images
        run: |
          docker compose build

      - name: Deploy Services
        run: |
          docker compose down
          docker compose up -d
